### ISSUE TITLE
运行问题

### ISSUE THREAD

**Issue by SunnysideBao** [huiminren/RobustVAE#1]
Hello, in running RVAE in pytorch, what is the number of autoencoders and alternating iterations? Why do I always fail to achieve the desired results? Looking forward to your reply

**Comment by huiminren** [comment]
Hi, thanks for your intresting. We implemented CelebA dataset with Pytorch. The default parameters had been set in main function. The alternating iterestions are 10 and the epochs of each autoencoder are 20. If you have further questions, please let us know.
